/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNILab */

#ifndef _Included_JNILab
#define _Included_JNILab
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNILab
 * Method:    testChar
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_JNILab_testChar
  (JNIEnv *, jobject, jchar);

#ifdef __cplusplus
}
#endif
#endif
