/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello */

#ifndef _Included_hello
#define _Included_hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello
 * Method:    get_random
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hello_get_1random
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
